# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  gmail_username: Your_Username
  gmail_password: Your_Password
  secret_key_base: d6ef39e32a3bb8cce20e3a50af206b9d0c7790455c8e5eb8d9ed4401caae6204eb5570eb3835a0f4b713bc3aea3b6ddc7c7e66405cecd7b3f9bbf5ccf94fc9c9

test:
  secret_key_base: 268d5efdae4d709e3fb01bc15ceb6dc05faac64ba87d57670a4b9f7f392203cce688c53c414ebceac4ca55301bcbc8fe537659edf91e55a90b138ac74265f1ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
