require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoinExchangesController do

  # This should return the minimal set of attributes required to create a valid
  # CoinExchange. As you add validations to CoinExchange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "coin" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoinExchangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coin_exchanges as @coin_exchanges" do
      coin_exchange = CoinExchange.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coin_exchanges).should eq([coin_exchange])
    end
  end

  describe "GET show" do
    it "assigns the requested coin_exchange as @coin_exchange" do
      coin_exchange = CoinExchange.create! valid_attributes
      get :show, {:id => coin_exchange.to_param}, valid_session
      assigns(:coin_exchange).should eq(coin_exchange)
    end
  end

  describe "GET new" do
    it "assigns a new coin_exchange as @coin_exchange" do
      get :new, {}, valid_session
      assigns(:coin_exchange).should be_a_new(CoinExchange)
    end
  end

  describe "GET edit" do
    it "assigns the requested coin_exchange as @coin_exchange" do
      coin_exchange = CoinExchange.create! valid_attributes
      get :edit, {:id => coin_exchange.to_param}, valid_session
      assigns(:coin_exchange).should eq(coin_exchange)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoinExchange" do
        expect {
          post :create, {:coin_exchange => valid_attributes}, valid_session
        }.to change(CoinExchange, :count).by(1)
      end

      it "assigns a newly created coin_exchange as @coin_exchange" do
        post :create, {:coin_exchange => valid_attributes}, valid_session
        assigns(:coin_exchange).should be_a(CoinExchange)
        assigns(:coin_exchange).should be_persisted
      end

      it "redirects to the created coin_exchange" do
        post :create, {:coin_exchange => valid_attributes}, valid_session
        response.should redirect_to(CoinExchange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coin_exchange as @coin_exchange" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoinExchange.any_instance.stub(:save).and_return(false)
        post :create, {:coin_exchange => { "coin" => "invalid value" }}, valid_session
        assigns(:coin_exchange).should be_a_new(CoinExchange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoinExchange.any_instance.stub(:save).and_return(false)
        post :create, {:coin_exchange => { "coin" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coin_exchange" do
        coin_exchange = CoinExchange.create! valid_attributes
        # Assuming there are no other coin_exchanges in the database, this
        # specifies that the CoinExchange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoinExchange.any_instance.should_receive(:update).with({ "coin" => "" })
        put :update, {:id => coin_exchange.to_param, :coin_exchange => { "coin" => "" }}, valid_session
      end

      it "assigns the requested coin_exchange as @coin_exchange" do
        coin_exchange = CoinExchange.create! valid_attributes
        put :update, {:id => coin_exchange.to_param, :coin_exchange => valid_attributes}, valid_session
        assigns(:coin_exchange).should eq(coin_exchange)
      end

      it "redirects to the coin_exchange" do
        coin_exchange = CoinExchange.create! valid_attributes
        put :update, {:id => coin_exchange.to_param, :coin_exchange => valid_attributes}, valid_session
        response.should redirect_to(coin_exchange)
      end
    end

    describe "with invalid params" do
      it "assigns the coin_exchange as @coin_exchange" do
        coin_exchange = CoinExchange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoinExchange.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin_exchange.to_param, :coin_exchange => { "coin" => "invalid value" }}, valid_session
        assigns(:coin_exchange).should eq(coin_exchange)
      end

      it "re-renders the 'edit' template" do
        coin_exchange = CoinExchange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoinExchange.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin_exchange.to_param, :coin_exchange => { "coin" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coin_exchange" do
      coin_exchange = CoinExchange.create! valid_attributes
      expect {
        delete :destroy, {:id => coin_exchange.to_param}, valid_session
      }.to change(CoinExchange, :count).by(-1)
    end

    it "redirects to the coin_exchanges list" do
      coin_exchange = CoinExchange.create! valid_attributes
      delete :destroy, {:id => coin_exchange.to_param}, valid_session
      response.should redirect_to(coin_exchanges_url)
    end
  end

end
