require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoinsController do

  # This should return the minimal set of attributes required to create a valid
  # Coin. As you add validations to Coin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coins as @coins" do
      coin = Coin.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coins).should eq([coin])
    end
  end

  describe "GET show" do
    it "assigns the requested coin as @coin" do
      coin = Coin.create! valid_attributes
      get :show, {:id => coin.to_param}, valid_session
      assigns(:coin).should eq(coin)
    end
  end

  describe "GET new" do
    it "assigns a new coin as @coin" do
      get :new, {}, valid_session
      assigns(:coin).should be_a_new(Coin)
    end
  end

  describe "GET edit" do
    it "assigns the requested coin as @coin" do
      coin = Coin.create! valid_attributes
      get :edit, {:id => coin.to_param}, valid_session
      assigns(:coin).should eq(coin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coin" do
        expect {
          post :create, {:coin => valid_attributes}, valid_session
        }.to change(Coin, :count).by(1)
      end

      it "assigns a newly created coin as @coin" do
        post :create, {:coin => valid_attributes}, valid_session
        assigns(:coin).should be_a(Coin)
        assigns(:coin).should be_persisted
      end

      it "redirects to the created coin" do
        post :create, {:coin => valid_attributes}, valid_session
        response.should redirect_to(Coin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coin as @coin" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coin.any_instance.stub(:save).and_return(false)
        post :create, {:coin => { "name" => "invalid value" }}, valid_session
        assigns(:coin).should be_a_new(Coin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coin.any_instance.stub(:save).and_return(false)
        post :create, {:coin => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coin" do
        coin = Coin.create! valid_attributes
        # Assuming there are no other coins in the database, this
        # specifies that the Coin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coin.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => coin.to_param, :coin => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested coin as @coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => valid_attributes}, valid_session
        assigns(:coin).should eq(coin)
      end

      it "redirects to the coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => valid_attributes}, valid_session
        response.should redirect_to(coin)
      end
    end

    describe "with invalid params" do
      it "assigns the coin as @coin" do
        coin = Coin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coin.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin.to_param, :coin => { "name" => "invalid value" }}, valid_session
        assigns(:coin).should eq(coin)
      end

      it "re-renders the 'edit' template" do
        coin = Coin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coin.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin.to_param, :coin => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coin" do
      coin = Coin.create! valid_attributes
      expect {
        delete :destroy, {:id => coin.to_param}, valid_session
      }.to change(Coin, :count).by(-1)
    end

    it "redirects to the coins list" do
      coin = Coin.create! valid_attributes
      delete :destroy, {:id => coin.to_param}, valid_session
      response.should redirect_to(coins_url)
    end
  end

end
